### ISSUE TITLE
What to Use?

### ISSUE THREAD

**Issue by ARCTaylor** [ARCTaylor-Development/Hustle#2]
We need to decide what software we want to use for development. This includes but is not limited to:

- Framework (e.g. Vue, React, Angular)
- Hosting Service (e.g. HostGator, BlueHost, A2 Hosting)
- Database (e.g. MongoDB, Amazon RDS, Oracle)
- Authentication (e.g. Firbase, Auth0)
- Tooling (i.e. linting, auto formatting, debugging, etc. | e.g. yarn/npm, prettier, etc.)
- Libraries/Packages (e.g. Quasar, Bootstrap, Tailwind)
- Node Js. Just node

**Comment by Artxmisery** [comment]
Framework-wise, my vote is for Vue. It's the only one I have the slightest bit of experience in and will probably end up being slightly more newbie-friendly (which should probably be part of the consideration).
For hosting, I think we're probably fine to delay that for a little bit, but AWS Amplify does offer a year of free hosting for apps of our likely size.
For much the same reason, my vote is Amazon RDS for the database. For our purposes and timeframe it'll be free (I think).
Userfront gets my vote for authentication, since it'll be completely free for us and is more lightweight/versatile than most of the other options. We also probably aren't too concerned about legacy support, which would be the main drawback for Userfront.
For tools, yarn and prettier are definitely worth an inclusion. Parcel is also probably a good idea, since having everyone work off the same one webserver for development and testing stuff seems... impractical, to say the least.
Libraries deserve a separate issue methinks, since that'll probably be more of an evolving process than most of the rest of our selections here.
node.js

**Comment by ARCTaylor** [comment]
Definitely agree with Vue. I don't have any issues with AWS Amplify or RDS; I don't know too much about them but they sound fine and if we have issues we can easily pivot since they're free. Similar story for Userfront. Yarn, prettier, node are required. And I don't really know what Parcel is.

**Comment by Bedrock206** [comment]
Vue sounds interesting.

AWS also sounds viable

My vote is for MongoDB because I have some experience with it, and know that it is very powerful (though very much beyond the scope of this project to be fair)

No idea on auth stuff

^

^

Node.js

**Comment by ARCTaylor** [comment]
I know that MongoDB is popular but I don't know about pricing. Also, there could potentially be benefits to using multiple AWS platforms together.

**Comment by ARCTaylor** [comment]
Also, I disagree that there's no need to host immediately. Obviously we'll mainly be testing stuff with localhost but I think it's best to get that infrastructure built out while the project is small and simple.

**Comment by Artxmisery** [comment]
MongoDB has a free, shared version that appears to just package other hosting services? Particularly notable is that one option is just Amazon RDS with more limits. I'm not sure that MongoDB has enough benefits over RDS to justify the much more limited resources.
